# Compose file for local development, external services only.

version: '3'

services:
  db-sdk:
    image: postgres:14.1
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=e2esdk
    volumes:
      - .volumes/storage/db-sdk:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      start_period: 3s
      retries: 5

  db-app:
    image: postgres:14.1
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - .volumes/storage/db-app:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      start_period: 3s
      retries: 50

  hasura:
    build: ./src/hasura
    env_file: ./src/hasura/.env
    restart: unless-stopped
    ports:
      - '8080:8080'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      db-app:
        condition: service_healthy
