name: CI
on:
  - push
  - pull_request

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Get yarn cache directory path
        id: init
        shell: bash
        run: |
          echo "::set-output name=yarn_cache::$(yarn cache dir)"
          #
          echo "Node $(node --version)"
          echo "NPM $(npm --version)"
          echo "Npx $(npx --version)"
          echo "Yarn $(yarn --version)"
          #
          # HACK(douglasduteil): symlink node to /usr/bin/node
          # Avoid the npx jest error on e2e tests
          #   /usr/bin/env: 'node': No such file or directory
          # see https://github.com/nodejs/node-v0.x-archive/issues/3911
          sudo ln -s $(which node) /usr/bin/node
      - name: Installing
        run: yarn --frozen-lockfile --perfer-offline --link-duplicates

      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test --coverage --coverageReporters=lcov --coverageReporters=text-summary

      # - name: Send test coverage to codecov
      #   continue-on-error: true
      #   uses: codecov/codecov-action@v2

      - name: Build
        run: yarn build

      # - name: Functional tests
      #   run: yarn e2e

      # - name: Build to lib folder for archives
      #   run: yarn build --outDir lib

      # - name: Archive lib components
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: components
      #     path: lib/
